# UMI-Aware Targeted DNA-Sequencing Pipeline Configuration

# Input data paths
input:
  fastq_dir: "results/fastq"
  target_bed: "data/design/raindance.bed"

# Reference genome
reference:
  genome: "data/genomics-reference/hs37d5/hs37d5.fa"  # Update this path to your hs37d5 reference
  dbsnp: "data/genomics-reference/hs37d5/dbsnp_138.b37.bgz.vcf.gz"  # Update this path to your dbSNP VCF
# UMI configuration
umi:
  # UMI pattern for umi_tools extract
  # Common patterns:
  # - NNNNNNNN for 8bp UMI at 5' end
  # - NNNNNNNNXXXXXX for 8bp UMI + 6bp constant region
  barcode_pattern: "NNNNNNNN"  # Adjust based on your UMI structure
  barcode_pattern2: ""  # For paired-end UMI patterns, leave empty if not needed

# Tool-specific parameters
tools:
  fastqc:
    threads: 2
  
  bwa:
    threads: 18
  
  freebayes:
    threads: 24
    # Additional parameters can be added here
    min_base_quality: 20
    min_mapping_quality: 20
  
  manta:
    threads: 18
  
  msisensor:
    threads: 24

# Resource allocation
resources:
  default_mem_mb: 4000
  alignment_mem_mb: 8000
  variant_calling_mem_mb: 6000

# RNA-seq specific settings
rnaseq:
  input:
    fastq_dir: "results/fastq_rna"
  bbsplit:
    human_ref: "data/genomics-reference/hs37d5/hs37d5.fa"
    mouse_ref: "data/genomics-reference/hs37d5/hs37d5.fa"
  STAR:
    ref: "data/genomics-reference/hs37d5/STAR/"
  rsem:
    ref: "data/genomics-reference/hs37d5/rsem_ref/rsem_ref"
  cicero:
    fusion_annot: "data/genomics-reference/hs37d5/hs37d5.fa"

